server:
  port: 8890

spring:
  config:
    name: marketing-rpc-test

dubbo:
  application:
    name: marketing-rpc-test
    version: 1.0
  registry:
    address: nacos://127.0.0.1:8848
  protocol:
    name: dubbo
    port: -1